DECLARE 
    MINHAEXE EXECPTION;
    n NUMBER := 10;
    
BEGIN
    FOR i IN &i .. &n LOOP
    dbms_output.put_line(i * i);
    IF i * 2 = 10 THEN
        RAISE MINHAEXE;
        
    END IF;
END LOOP;

EXCEPTION 
    WHEN MINHAEXE THEN
        RAISE_APPLICATION_ERROR(-20015, 'Você caiu na execção');
END;
    
    
    
SELECT CODIGO_CLIETE,
 (SELECT NOME_CLIENTE
    FROM CLIENTE
    WHERE CODIGO_CLIENTE =C.CODIGO_CLIENTE) NOME
    FROM ENDERECO_CLIENTE C
    WHERE CODIGO_CLIENTE
        IN (SELECT CODIGO_CLIENTE FROM CLIENTE);
