SELECT CODIGO_CLIETE,
 (SELECT NOME_CLIENTE
    FROM CLIENTE
    WHERE CODIGO_CLIENTE =C.CODIGO_CLIENTE) NOME
    FROM ENDERECO_CLIENTE C
    WHERE CODIGO_CLIENTE
        IN (SELECT CODIGO_CLIENTE FROM CLIENTE);