SET SERVEROUT ON;

CREATE OR REPLACE FUNCTION PROCEDURE_FGTS IS
V_VALOR NUMBER;
BEGIN
V_VALOR := CALCULA_FGTS(5000);
DBMS_OUTPUT.PUTLINE('o VALOR DO fgts É: ' || TO_CHAR(V_VALOR));
END PROCEDURE_FGTS;

EXEC PROCEDURE_FGTS();